language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
      dist: xenial
      sudo: true

    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true

before_install:
  - pip install poetry 

install:
  - poetry install -v

script:
  - tox

after_success:
  - coverage combine
  - coverage report
  - codecov