language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
      dist: xenial
      sudo: true

before_install:
  - pip install pipenv 

install:
  - pipenv install --dev

script:
  - tox

after_success:
  - coverage combine
  - coverage report
  - codecov